# Generated by Django 4.2 on 2025-12-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celular',
            name='lanzamiento',
        ),
    ]
